model:
  target: ldm.models.diffusion.ldm_ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "reference"
    image_size: 64
    channels: 3
    cond_stage_trainable: False
    concat_mode: False
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [5000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 224
        attention_resolutions: [ 8, 4, 2 ]   # 32, 16, 8, 4   
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4 ]  # 32, 16, 8, 4, 2      
        num_heads: 8
        use_spatial_transformer: True
        context_dim: 768
        transformer_depth: 1
        use_checkpoint: True

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 3
        monitor: "val/rec_loss"
        ckpt_path: "models/kl-f4-wheat.ckpt"
        ddconfig:
          double_z: True
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenViTMAE

data:
  target: utils.utils.DataloaderFromConfig
  params:
    batch_size: 16
    num_workers: 8
    train:
      target: utils.wheat_dataset.wheatUnconditionalTrain
      params:
        txt_file: "datasets/wheat/train_ldm.txt"
        data_root: "datasets/wheat"
        ag_rate: 0.8
        flip_p: 0.5
        size: 256
    validation:
      target: utils.wheat_dataset.wheatUnconditionalValidation
      params:
        txt_file: "datasets/wheat/val_ldm.txt"
        data_root: "datasets/wheat"
        ag_rate: 0
        flip_p: 0
        size: 256

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 10000
        max_images: 4
        increase_log_steps: False


  trainer:
    benchmark: True
    max_steps: 315000
